name: formatter-all

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled ]

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.label.name == 'format_all') }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # Skip formatting if the commit message contains 'upstream' to avoid formatting on upstream merges
      - name: Check for upstream commit
        id: check_commit
        run: |
          if [[ "$(git log -1 --pretty=%B)" == *"upstream"* ]]; then
            echo "::set-output name=skip::true"
          else
            echo "::set-output name=skip::false"
          fi

      - name: Skip format if upstream merge
        if: steps.check_commit.outputs.skip == 'true'
        run: echo "Skipping formatting due to upstream merge"

      - uses: actions/setup-node@v3
        if: steps.check_commit.outputs.skip != 'true'
        with:
          node-version: "16"

      - name: Install stylua and format files
        if: steps.check_commit.outputs.skip != 'true'
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v0.18.0
          args: -- .

      - name: Format files with Prettier
        if: steps.check_commit.outputs.skip != 'true'
        run: |
            npx prettier --write '**/*.{ts,js,css,html}'

      - name: Update repo before push
        if: steps.check_commit.outputs.skip != 'true'
        run: |
          git pull

      - name: Commit changes and push current branch
        if: steps.check_commit.outputs.skip != 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: ESX GITHUB ACTIONS BOT
          commit_user_email: esx-github-actions-bot@users.noreply.github.com
          commit_message: :art:Code formatted in all files
